const state={events:[],weekStart:null,selected:null,teacher:""};
const ru=new Intl.DateTimeFormat("ru-RU",{weekday:"short",day:"numeric",month:"short"});
const titleFmt=new Intl.DateTimeFormat("ru-RU",{weekday:"long",day:"numeric",month:"long"});
const iso=d=>d.toISOString().slice(0,10);
const localDate=s=>new Date(`${s}T12:00:00`);
const monday=d=>{const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));return x};
function eventFor(date){return state.events.filter(e=>e.date===date&&(!state.teacher||e.teacher===state.teacher));}
function renderWeek(){const box=document.querySelector("#week");box.textContent="";for(let i=0;i<7;i++){const d=new Date(state.weekStart);d.setDate(d.getDate()+i);const key=iso(d), b=document.createElement("button");b.className=`day ${key===state.selected?"selected":""} ${eventFor(key).length?"has-lessons":""}`;b.innerHTML=`<span>${ru.format(d).split(",")[0]}</span><strong>${d.getDate()}</strong>`;b.onclick=()=>{state.selected=key;render()};box.append(b)}}
function ics(e){const stamp=x=>x.replaceAll("-","").replaceAll(":","")+"00";const start=stamp(`${e.date}T${e.start}:`.replace("T","T"));const end=stamp(`${e.date}T${e.end}:`);return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:${e.id}@uitp26\r\nDTSTART:${start}\r\nDTEND:${end}\r\nSUMMARY:${e.subject.replaceAll(",","\\,")}\r\nDESCRIPTION:Преподаватель: ${e.teacher}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`}
function exportIcs(e){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([ics(e)],{type:"text/calendar"}));a.download=`УИТП-26-${e.date}.ics`;a.click();URL.revokeObjectURL(a.href)}
function renderLessons(){const list=document.querySelector("#lessons"),events=eventFor(state.selected);document.querySelector("#day-title").textContent=titleFmt.format(localDate(state.selected));document.querySelector("#lesson-count").textContent=events.length?`${events.length} ${events.length===1?"занятие":"занятия"}`:"";list.textContent="";if(!events.length){list.innerHTML='<div class="empty">На этот день занятий нет</div>';return}const t=document.querySelector("#lesson-template");events.forEach(e=>{const n=t.content.cloneNode(true);n.querySelector(".lesson-time").textContent=`${e.start}–${e.end}`;n.querySelector("h3").textContent=e.subject;n.querySelector(".teacher-name").textContent=e.teacher;n.querySelector(".lesson-detail").textContent=e.details;n.querySelector(".calendar").onclick=()=>exportIcs(e);list.append(n)})}
function render(){renderWeek();renderLessons()}
function setWeek(offset){state.weekStart.setDate(state.weekStart.getDate()+offset*7);state.selected=iso(state.weekStart);render()}
const data=window.SCHEDULE_DATA;state.events=data.events;const teachers=[...new Set(data.events.map(e=>e.teacher).filter(x=>x&&x!=="Не указан"))].sort((a,b)=>a.localeCompare(b,"ru"));const select=document.querySelector("#teacher");teachers.forEach(x=>select.add(new Option(x,x)));select.onchange=e=>{state.teacher=e.target.value;render()};const first=localDate(data.events[0].date);state.weekStart=monday(first);state.selected=iso(first);document.querySelector("#subtitle").textContent=`${data.events.length} занятий · ${data.source}`;render();
document.querySelector("#previous").onclick=()=>setWeek(-1);document.querySelector("#next").onclick=()=>setWeek(1);document.querySelector("#today").onclick=()=>{const today=iso(new Date());const next=state.events.find(e=>e.date>=today);state.selected=next?next.date:state.events[0].date;state.weekStart=monday(localDate(state.selected));render()};
